services:
  test-asg-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-asg-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      # Mount current directory to preserve app.log file
      - ./:/app/host-logs:ro
      - logs-volume:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

volumes:
  logs-volume:

networks:
  app-network:
    driver: bridge
